spring:
  application:
    name: users
    version: @project.version@
  cloud:
    discovery:
      enabled: true
      eureka:
        instance:
          hostname: localhost
    client:
      hostname: localhost
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    enabled: true
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  security:
    enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 3600s
  redis:
    host: redis
    port: 6379
    ssl:
      enabled: false
    timeout: 5000
    jedis:
      pool:
        max-idle: 10
        min-idle: 1
        max-total: 20
  flyway:
    user: gl_user
    password: gl_user
    locations: classpath:db/migration
    table: FLYWAY_SCHEMA_HISTORY

server:
  port: 8180
  servlet:
    context-path: /users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    enabled: true
    exporter:
      zipkin:
        enabled: true
        url: http://localhost:9411/api/v2/spans

jwt:
  public:
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvxa26xwc/QrUNFAKGjvUv2DB3uL17DdJ8qSzB7GUzZJ0+aPbYGW1iR+PmAiZqvIj/1F6iH3N4zoIS560UrHevhE1wKzqTIPL2wdSNV4TONAnAVbEmRjTzX/kH3woSU0ZXu8BG1Xg8/D+u38aWSOX
      5nisxRyGthw//fo669Myon3XWRjS47CWLVI19vG0tplReAYH7eNKztynKGJMvb793dd/a2qQA4ggodwYzwnNGdkLqYgDxyniVDllF4taONgBIlzKbWLqzbT1z8MzeJHNgXSEH3vhLg3cwBt8VsxUvyqCBHvEqDw2zFLbFpCRRxnduortihTPWOOgwYq5gU7SBwIDAQAB
      -----END PUBLIC KEY-----

  private:
    key: classpath:private.key

logstash:
  destination: localhost:5000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/glaiss?TimeZone=America/Sao_Paulo
    username: gl_user
    password: gl_user
    driver-class-name: org.postgresql.Driver
  opensearch:
    host: http://localhost:9200
    index: logs-app

xray:
  daemon-address: 127.0.0.1:2000
  trade:
    id: ${XRAY_TRADE_ID:9f27d75e-9752-4ff6-9b19-195b1f19022e}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  flyway:
    user: ${USER_DB}
    password: ${PASSWORD_DB}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    discovery:
      eureka:
        instance:
          hostname: prod-hostname
    client:
      hostname: prod-hostname
eureka:
  client:
    service-url:
      defaultZone: ${URL_DISCOVERY}
server:
  port: ${PORT}
logstash:
  destination: ${LOGSTASH}