CREATE TABLE IF NOT EXISTS USUARIOS (
  ID UUID NOT NULL,
  USERNAME VARCHAR(100) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIVILEGIO VARCHAR(30) NOT NULL,
  IS_ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_USUARIOS_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKENS (
  ID UUID NOT NULL,
  TOKEN VARCHAR(255) NOT NULL,
  USUARIO_ID UUID NOT NULL,
  EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  REVOKED BOOLEAN DEFAULT FALSE NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_REFRESH_TOKENS PRIMARY KEY (ID),
  CONSTRAINT UK_REFRESH_TOKENS_TOKEN UNIQUE (TOKEN, USUARIO_ID),
  CONSTRAINT FK_REFRESH_TOKENS_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIOS (ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_REFRESH_TOKENS_TOKEN
ON REFRESH_TOKENS (TOKEN);

CREATE INDEX IF NOT EXISTS IDX_REFRESH_TOKENS_USUARIO
ON REFRESH_TOKENS (USUARIO_ID);



