CREATE TABLE IF NOT EXISTS USUARIOS (
  ID UUID NOT NULL,
  USERNAME VARCHAR(100) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIVILEGIO VARCHAR(30) NOT NULL,
  IS_ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  CONSTRAINT PK_USUARIOS_ID PRIMARY KEY (ID)
);

